// <auto-generated />
using System;
using HealthVerse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthVerse.Infrastructure.Migrations
{
    [DbContext(typeof(HealthVerseDbContext))]
    [Migration("20251230181523_AddUserNotificationPreferences")]
    partial class AddUserNotificationPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthVerse.Competition.Domain.Entities.LeagueConfig", b =>
                {
                    b.Property<string>("TierName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DemotePercentage")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRoomSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20);

                    b.Property<int>("MinRoomSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("PromotePercentage")
                        .HasColumnType("integer");

                    b.Property<int>("TierOrder")
                        .HasColumnType("integer");

                    b.HasKey("TierName");

                    b.HasIndex("TierOrder")
                        .IsUnique();

                    b.ToTable("LeagueConfigs", "competition");

                    b.HasData(
                        new
                        {
                            TierName = "ISINMA",
                            DemotePercentage = 0,
                            MaxRoomSize = 20,
                            MinRoomSize = 10,
                            PromotePercentage = 30,
                            TierOrder = 1
                        },
                        new
                        {
                            TierName = "ANTRENMAN",
                            DemotePercentage = 10,
                            MaxRoomSize = 20,
                            MinRoomSize = 10,
                            PromotePercentage = 20,
                            TierOrder = 2
                        },
                        new
                        {
                            TierName = "TEMPO",
                            DemotePercentage = 10,
                            MaxRoomSize = 20,
                            MinRoomSize = 10,
                            PromotePercentage = 20,
                            TierOrder = 3
                        },
                        new
                        {
                            TierName = "FORM",
                            DemotePercentage = 10,
                            MaxRoomSize = 20,
                            MinRoomSize = 10,
                            PromotePercentage = 20,
                            TierOrder = 4
                        },
                        new
                        {
                            TierName = "KONDISYON",
                            DemotePercentage = 10,
                            MaxRoomSize = 20,
                            MinRoomSize = 10,
                            PromotePercentage = 20,
                            TierOrder = 5
                        },
                        new
                        {
                            TierName = "DAYANIKLILIK",
                            DemotePercentage = 10,
                            MaxRoomSize = 20,
                            MinRoomSize = 10,
                            PromotePercentage = 20,
                            TierOrder = 6
                        },
                        new
                        {
                            TierName = "SAMPIYON",
                            DemotePercentage = 20,
                            MaxRoomSize = 20,
                            MinRoomSize = 10,
                            PromotePercentage = 0,
                            TierOrder = 7
                        });
                });

            modelBuilder.Entity("HealthVerse.Competition.Domain.Entities.LeagueMember", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointsInRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("RankSnapshot")
                        .HasColumnType("integer");

                    b.HasKey("RoomId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LeagueMembers_UserId");

                    b.ToTable("LeagueMembers", "competition");
                });

            modelBuilder.Entity("HealthVerse.Competition.Domain.Entities.LeagueRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("IsProcessed")
                        .HasDatabaseName("IX_LeagueRooms_Unprocessed")
                        .HasFilter("\"IsProcessed\" = false");

                    b.HasIndex("Tier", "UserCount")
                        .HasDatabaseName("IX_LeagueRooms_Allocate");

                    b.ToTable("LeagueRooms", "competition");
                });

            modelBuilder.Entity("HealthVerse.Competition.Domain.Entities.UserPointsHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LeagueRank")
                        .HasColumnType("integer");

                    b.Property<string>("PeriodId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TierAtTime")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PeriodType", "PeriodId")
                        .HasDatabaseName("IX_UserPointsHistory_Period");

                    b.HasIndex("UserId", "PeriodType", "CreatedAt")
                        .HasDatabaseName("IX_UserPointsHistory_User");

                    b.HasIndex("UserId", "PeriodType", "PeriodId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserPointsHistory_UserPeriod");

                    b.ToTable("UserPointsHistory", "competition");
                });

            modelBuilder.Entity("HealthVerse.Gamification.Domain.Entities.MilestoneReward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("FreezeReward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("IconName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PointsReward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_MilestoneRewards_Code");

                    b.HasIndex("IsActive", "Metric")
                        .HasDatabaseName("IX_MilestoneRewards_Metric");

                    b.ToTable("MilestoneRewards", "gamification");
                });

            modelBuilder.Entity("HealthVerse.Gamification.Domain.Entities.PointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceIdText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("PointTransactions", "gamification");
                });

            modelBuilder.Entity("HealthVerse.Gamification.Domain.Entities.UserDailyStats", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("DailySteps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "LogDate");

                    b.ToTable("UserDailyStats", "gamification");
                });

            modelBuilder.Entity("HealthVerse.Gamification.Domain.Entities.UserMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClaimed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MilestoneRewardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserMilestones_User");

                    b.HasIndex("UserId", "MilestoneRewardId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserMilestones_UserMilestone");

                    b.ToTable("UserMilestones", "gamification");
                });

            modelBuilder.Entity("HealthVerse.Gamification.Domain.Entities.UserStreakFreezeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StreakCountAtTime")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("UsedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserStreakFreezeLog_User");

                    b.HasIndex("UserId", "UsedDate")
                        .IsUnique()
                        .HasDatabaseName("UX_UserStreakFreezeLog_UserDate");

                    b.ToTable("UserStreakFreezeLog", "gamification");
                });

            modelBuilder.Entity("HealthVerse.Identity.Domain.Entities.AuthIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique()
                        .HasDatabaseName("UX_AuthIdentities_FirebaseUid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuthIdentities_User");

                    b.HasIndex("Provider", "ProviderEmail")
                        .HasDatabaseName("IX_AuthIdentities_ProviderEmail");

                    b.ToTable("AuthIdentities", "identity");
                });

            modelBuilder.Entity("HealthVerse.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvatarId")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("integer");

                    b.Property<int>("FollowingCount")
                        .HasColumnType("integer");

                    b.Property<int>("FreezeInventory")
                        .HasColumnType("integer");

                    b.Property<bool>("HealthPermissionGranted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("HealthPermissionGrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("LastStreakDate")
                        .HasColumnType("date");

                    b.Property<int>("LongestStreakCount")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("SelectedTitleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StreakCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDuelsWon")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGlobalMissions")
                        .HasColumnType("integer");

                    b.Property<long>("TotalPoints")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalTasksCompleted")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("HealthVerse.Missions.Domain.Entities.GlobalMission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("CurrentValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HiddenRewardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<string>("TargetMetric")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("STEPS");

                    b.Property<long>("TargetValue")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_GlobalMissions_Status");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_GlobalMissions_TimeWindow");

                    b.ToTable("GlobalMissions", "missions", t =>
                        {
                            t.HasCheckConstraint("CHK_GlobalMissions_CurrentValue", "\"CurrentValue\" >= 0");

                            t.HasCheckConstraint("CHK_GlobalMissions_Status", "\"Status\" IN ('DRAFT','ACTIVE','FINISHED','CANCELLED')");

                            t.HasCheckConstraint("CHK_GlobalMissions_TargetValue", "\"TargetValue\" > 0");

                            t.HasCheckConstraint("CHK_GlobalMissions_TimeWindow", "\"EndDate\" > \"StartDate\"");
                        });
                });

            modelBuilder.Entity("HealthVerse.Missions.Domain.Entities.GlobalMissionContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_GlobalMissionContributions_Idempotency");

                    b.HasIndex("MissionId", "CreatedAt")
                        .HasDatabaseName("IX_GlobalMissionContrib_MissionTime");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_GlobalMissionContrib_UserTime");

                    b.ToTable("GlobalMissionContributions", "missions", t =>
                        {
                            t.HasCheckConstraint("CHK_GlobalMissionContributions_Amount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("HealthVerse.Missions.Domain.Entities.GlobalMissionParticipant", b =>
                {
                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("ContributionValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsRewardClaimed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MissionId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_GlobalMissionParticipants_ByUser");

                    b.ToTable("GlobalMissionParticipants", "missions", t =>
                        {
                            t.HasCheckConstraint("CHK_GlobalMissionParticipants_ContributionValue", "\"ContributionValue\" >= 0");
                        });
                });

            modelBuilder.Entity("HealthVerse.Missions.Domain.Entities.WeeklyPartnerMission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("InitiatorLastPokeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InitiatorProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PartnerLastPokeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PartnerProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<string>("TargetMetric")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("STEPS");

                    b.Property<int>("TargetValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100000);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeekId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorId")
                        .HasDatabaseName("IX_WPM_Initiator");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("IX_WPM_Partner");

                    b.HasIndex("WeekId")
                        .HasDatabaseName("IX_WPM_ByWeek");

                    b.HasIndex("Id", "WeekId")
                        .IsUnique()
                        .HasDatabaseName("UX_WPM_IdWeek");

                    b.ToTable("WeeklyPartnerMissions", "missions", t =>
                        {
                            t.HasCheckConstraint("CHK_WPM_NoSelf", "\"InitiatorId\" <> \"PartnerId\"");

                            t.HasCheckConstraint("CHK_WPM_Progress", "\"InitiatorProgress\" >= 0 AND \"PartnerProgress\" >= 0");

                            t.HasCheckConstraint("CHK_WPM_Status", "\"Status\" IN ('ACTIVE','FINISHED','CANCELLED','EXPIRED')");

                            t.HasCheckConstraint("CHK_WPM_TargetValue", "\"TargetValue\" > 0");
                        });
                });

            modelBuilder.Entity("HealthVerse.Missions.Domain.Entities.WeeklyPartnerMissionSlot", b =>
                {
                    b.Property<string>("WeekId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.HasKey("WeekId", "UserId");

                    b.HasIndex("MissionId")
                        .HasDatabaseName("IX_WPMSlots_Mission");

                    b.ToTable("WeeklyPartnerMissionSlots", "missions");
                });

            modelBuilder.Entity("HealthVerse.Notifications.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Notifications_Type");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Notifications_UserTime");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("IX_Notifications_UserUnread");

                    b.ToTable("Notifications", "notifications");
                });

            modelBuilder.Entity("HealthVerse.Notifications.Domain.Entities.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Push");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("IX_NotificationDeliveries_NotificationId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_NotificationDeliveries_UserId");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("IX_NotificationDeliveries_Status_ScheduledAt");

                    b.ToTable("NotificationDeliveries", "notification");
                });

            modelBuilder.Entity("HealthVerse.Notifications.Domain.Entities.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PushToken")
                        .IsUnique()
                        .HasDatabaseName("UX_UserDevices_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserDevices_User");

                    b.ToTable("UserDevices", "notifications");
                });

            modelBuilder.Entity("HealthVerse.Notifications.Domain.Entities.UserNotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("QuietHoursEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("QuietHoursStart")
                        .HasColumnType("time without time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserNotificationPreferences_User");

                    b.HasIndex("UserId", "Category")
                        .IsUnique()
                        .HasDatabaseName("UX_UserNotificationPreferences_User_Category");

                    b.ToTable("UserNotificationPreferences", "notifications");
                });

            modelBuilder.Entity("HealthVerse.Social.Domain.Entities.Duel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ChallengerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ChallengerLastPokeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChallengerScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("OpponentLastPokeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpponentScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Result")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("WAITING");

                    b.Property<string>("TargetMetric")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType")
                        .HasDatabaseName("IX_Duels_ActivityType");

                    b.HasIndex("ChallengerId")
                        .HasDatabaseName("IX_Duels_Challenger");

                    b.HasIndex("OpponentId")
                        .HasDatabaseName("IX_Duels_Opponent");

                    b.HasIndex("ChallengerId", "OpponentId")
                        .HasDatabaseName("IX_Duels_Pair");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Duels_Expire_WaitingCreatedAt");

                    b.ToTable("Duels", "social", t =>
                        {
                            t.HasCheckConstraint("CHK_Duels_ActiveHasEnd", "\"Status\" <> 'ACTIVE' OR \"EndDate\" IS NOT NULL");

                            t.HasCheckConstraint("CHK_Duels_ActiveHasStart", "\"Status\" <> 'ACTIVE' OR \"StartDate\" IS NOT NULL");

                            t.HasCheckConstraint("CHK_Duels_DurationDays", "\"DurationDays\" BETWEEN 1 AND 7");

                            t.HasCheckConstraint("CHK_Duels_ExpiredHasNoDates", "\"Status\" <> 'EXPIRED' OR (\"StartDate\" IS NULL AND \"EndDate\" IS NULL AND \"Result\" IS NULL)");

                            t.HasCheckConstraint("CHK_Duels_FinishedHasEndAndResult", "\"Status\" <> 'FINISHED' OR (\"EndDate\" IS NOT NULL AND \"Result\" IS NOT NULL)");

                            t.HasCheckConstraint("CHK_Duels_FinishedHasStart", "\"Status\" <> 'FINISHED' OR \"StartDate\" IS NOT NULL");

                            t.HasCheckConstraint("CHK_Duels_NoSelf", "\"ChallengerId\" <> \"OpponentId\"");

                            t.HasCheckConstraint("CHK_Duels_RejectedHasNoDates", "\"Status\" <> 'REJECTED' OR (\"StartDate\" IS NULL AND \"EndDate\" IS NULL AND \"Result\" IS NULL)");

                            t.HasCheckConstraint("CHK_Duels_Result", "\"Result\" IS NULL OR \"Result\" IN ('CHALLENGER_WIN','OPPONENT_WIN','BOTH_WIN','BOTH_LOSE')");

                            t.HasCheckConstraint("CHK_Duels_ResultOnlyWhenFinished", "\"Result\" IS NULL OR \"Status\" = 'FINISHED'");

                            t.HasCheckConstraint("CHK_Duels_Scores", "\"ChallengerScore\" >= 0 AND \"OpponentScore\" >= 0");

                            t.HasCheckConstraint("CHK_Duels_Status", "\"Status\" IN ('WAITING','ACTIVE','FINISHED','REJECTED','EXPIRED')");

                            t.HasCheckConstraint("CHK_Duels_TargetValue", "\"TargetValue\" > 0");

                            t.HasCheckConstraint("CHK_Duels_TimeOrder", "\"StartDate\" IS NULL OR \"EndDate\" IS NULL OR \"EndDate\" > \"StartDate\"");

                            t.HasCheckConstraint("CHK_Duels_WaitingHasNoDates", "\"Status\" <> 'WAITING' OR (\"StartDate\" IS NULL AND \"EndDate\" IS NULL AND \"Result\" IS NULL)");
                        });
                });

            modelBuilder.Entity("HealthVerse.Social.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FollowerId", "FollowingId");

                    b.HasIndex("FollowingId", "FollowerId")
                        .HasDatabaseName("IX_Friendships_ByFollowing");

                    b.ToTable("Friendships", "social", t =>
                        {
                            t.HasCheckConstraint("CHK_Friendships_NoSelf", "\"FollowerId\" <> \"FollowingId\"");
                        });
                });

            modelBuilder.Entity("HealthVerse.Social.Domain.Entities.UserBlock", b =>
                {
                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BlockerId", "BlockedId");

                    b.HasIndex("BlockedId")
                        .HasDatabaseName("IX_UserBlocks_Blocked");

                    b.HasIndex("BlockerId")
                        .HasDatabaseName("IX_UserBlocks_Blocker");

                    b.ToTable("UserBlocks", "social", t =>
                        {
                            t.HasCheckConstraint("CHK_UserBlocks_NoSelf", "\"BlockerId\" <> \"BlockedId\"");
                        });
                });

            modelBuilder.Entity("HealthVerse.Tasks.Domain.Entities.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BadgeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("RewardPoints")
                        .HasColumnType("integer");

                    b.Property<string>("TargetMetric")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TitleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType")
                        .HasDatabaseName("IX_TaskTemplates_Activity");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TaskTemplates_Active");

                    b.ToTable("TaskTemplates", "tasks");
                });

            modelBuilder.Entity("HealthVerse.Tasks.Domain.Entities.UserGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("TargetMetric")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CompletedAt")
                        .HasDatabaseName("IX_UserGoals_User_Completed");

                    b.HasIndex("UserId", "ValidUntil")
                        .HasDatabaseName("IX_UserGoals_User_Active");

                    b.ToTable("UserGoals", "tasks", t =>
                        {
                            t.HasCheckConstraint("CHK_UserGoals_Completed", "\"CompletedAt\" IS NULL OR \"CurrentValue\" >= \"TargetValue\"");
                        });
                });

            modelBuilder.Entity("HealthVerse.Tasks.Domain.Entities.UserInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ActivityType");

                    b.HasIndex("ActivityType")
                        .HasDatabaseName("IX_UserInterests_Activity");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserInterests_User");

                    b.ToTable("UserInterests", "tasks");
                });

            modelBuilder.Entity("HealthVerse.Tasks.Domain.Entities.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RewardClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("IX_UserTasks_Template");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_UserTasks_User_Status");

                    b.HasIndex("UserId", "ValidUntil")
                        .HasDatabaseName("IX_UserTasks_Active_ValidUntil");

                    b.ToTable("UserTasks", "tasks", t =>
                        {
                            t.HasCheckConstraint("CHK_UserTasks_CompletedAt", "\"Status\" <> 'COMPLETED' OR \"CompletedAt\" IS NOT NULL");

                            t.HasCheckConstraint("CHK_UserTasks_FailedAt", "\"Status\" <> 'FAILED' OR \"FailedAt\" IS NOT NULL");

                            t.HasCheckConstraint("CHK_UserTasks_RewardClaimedAt", "\"Status\" <> 'REWARD_CLAIMED' OR \"RewardClaimedAt\" IS NOT NULL");

                            t.HasCheckConstraint("CHK_UserTasks_RewardImpliesCompleted", "\"Status\" <> 'REWARD_CLAIMED' OR \"CompletedAt\" IS NOT NULL");

                            t.HasCheckConstraint("CHK_UserTasks_TimeWindow", "\"ValidUntil\" > \"AssignedAt\"");
                        });
                });

            modelBuilder.Entity("HealthVerse.Competition.Domain.Entities.LeagueMember", b =>
                {
                    b.HasOne("HealthVerse.Competition.Domain.Entities.LeagueRoom", null)
                        .WithMany("Members")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HealthVerse.SharedKernel.ValueObjects.WeekId", "WeekId", b1 =>
                        {
                            b1.Property<Guid>("LeagueMemberRoomId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("LeagueMemberUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("WeekId");

                            b1.HasKey("LeagueMemberRoomId", "LeagueMemberUserId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_LeagueMembers_WeekId");

                            b1.ToTable("LeagueMembers", "competition");

                            b1.WithOwner()
                                .HasForeignKey("LeagueMemberRoomId", "LeagueMemberUserId");
                        });

                    b.Navigation("WeekId")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthVerse.Competition.Domain.Entities.LeagueRoom", b =>
                {
                    b.HasOne("HealthVerse.Competition.Domain.Entities.LeagueConfig", null)
                        .WithMany()
                        .HasForeignKey("Tier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("HealthVerse.SharedKernel.ValueObjects.WeekId", "WeekId", b1 =>
                        {
                            b1.Property<Guid>("LeagueRoomId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("WeekId");

                            b1.HasKey("LeagueRoomId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_LeagueRooms_WeekId");

                            b1.ToTable("LeagueRooms", "competition");

                            b1.WithOwner()
                                .HasForeignKey("LeagueRoomId");
                        });

                    b.Navigation("WeekId")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthVerse.Gamification.Domain.Entities.PointTransaction", b =>
                {
                    b.OwnsOne("HealthVerse.SharedKernel.ValueObjects.IdempotencyKey", "IdempotencyKey", b1 =>
                        {
                            b1.Property<Guid>("PointTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("IdempotencyKey");

                            b1.HasKey("PointTransactionId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("PointTransactions", "gamification");

                            b1.WithOwner()
                                .HasForeignKey("PointTransactionId");
                        });

                    b.Navigation("IdempotencyKey")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthVerse.Identity.Domain.Entities.User", b =>
                {
                    b.OwnsOne("HealthVerse.Identity.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("HealthVerse.Identity.Domain.ValueObjects.Username", "Username", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("Username");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Username")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthVerse.Competition.Domain.Entities.LeagueRoom", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
